### ISSUE TITLE
incompatible with boost 1.76

### ISSUE THREAD

**Issue by ebbit1q** [twanvl/MagicSetEditor2#132]
boost's internal regex implementation has changed, the way that /src/util/regex.cpp subclasses the match_result class is not possible anymore. While questionable to begin with, this implementation is used everywhere in the code and would be hard to change. wxString is the worst, would replacing it with normal strings be an option?

**Comment by twanvl** [comment]
There are some plans for using std::string internally. I guess this issue means that this moves up in priority.

**Comment by twanvl** [comment]
If the only issue is inheriting from `boost::match_results`, then the simplest fix is actually to just make the match results a member of our `Regex::Results`.

**Comment by ebbit1q** [comment]
yes, I actually tried implementing it like that but it's harder than you think with the current way it is used in combination with boost's own functions, I think the best way to do this would be to use std::strings instead

**Comment by twanvl** [comment]
Switching to `std::string` (#135) doesn't help at all, because we would still need to use regex of unicode characters. A `boost::basic_regex<char>` will not work, because it is not Unicode aware, so you can produce invalid UTF-8.
If the error you get is the same as in #133, then this is not actually about `boost::regex` at all, rather it is about `boost::hash` or maybe some include order issue.

**Comment by ebbit1q** [comment]
I thought so too at first, but adding the missing header revealed that the header was missing because this hash isn't used at all anymore.

**Comment by ebbit1q** [comment]
thanks :+1:
