### ISSUE TITLE
v2.0.2-rc1 Set file quirks

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#14]
The 'set' file inside the .mse-set is saving as mse version 0.3.8 rather than 2.0.2/2.0.0. It has also removed the \r character, which doesn't seem to have affected anything (I did try to see if this was causing the missing styling issue from #3 but no changes), but does make the file less friendly to check though in regular Notepad.

**Comment by twanvl** [comment]
The version number in set files is intentional. It is set this way because the file format has not changed since 0.3.8, so in theory mse 0.3.8 should be able to open a set file saved with mse 2.0.2.

As for the \r: just use any other editor (or even notepad on windows 10). But if this is really important enough to people I could change it back.

**Comment by fenhl** [comment]
I'm in favor of keeping it as is. Using an editor that supports LF line breaks is a good idea anyway.

**Comment by CajunAvenger** [comment]
I do normally use Notepad++ but for whatever reason regular Notepad is the only one that will actually save changes to the file through 7zip, so it's what I use in that specific case.
I recognize its a niche and mostly unimportant case which is why it was the last on my list here.
