### ISSUE TITLE
v2.0.2-rc1 - Card Visual errors

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#4]
I've loaded a few 2.0.1 sets with 2.0.2 an ran into a few visual errors

- Card arts are not being loaded, and "card.image" returns blank in the console tab. However, if you make a copy of a card, it does have the image, and saving the file and reopening on 2.0.1 still loads the images there.

- Field locations are now updating on hovering over a card rather than changing to a card, so moving between cards on different templates or with specific styling initially result in messy images. This effect sometimes also happens on the Style tab until you change an option, but I'm not sure if there's a particular trigger there yet. [Image](https://cdn.discordapp.com/attachments/443557716842250240/704519367672463380/unknown.png)

- The "type 2" field flickers at random as the cursor moves around. It doesn't seem to be tied to where the mouse cursor is, and is happening on different frames. It appears to be the only field doing this. [Image](https://cdn.discordapp.com/attachments/443557716842250240/704520047330066513/unknown.png)

**Comment by CajunAvenger** [comment]
These look to be mostly fixed now on the most recent code, with one holdout that I suspect is a template doing more than expected :D 

The images are back, the type field has stopped flickering, and changing templates now has smooth field transitions, but cards on the same template that have quite different styling options are still going a bit weird. This is most prevalent in the Mainframe templates that allow for things like Planeswalkers and Levelers with variable height textboxes, and their ability to stack many different frames.

[Here](https://www.dropbox.com/s/k7ptiaqtea7bv45/202%20Mini%20Test.zip?dl=0) is a set file with 4 of the cards on that frame that are having trouble with the jumping fields, plus the template, its include folder, and the magic.mse-game updated to the recent code changes (nil equality, = -> ==, and required returns to if statements).

**Comment by twanvl** [comment]
The problem is (probably) with scripted style properties depending on other scripted style properties. For example, in the leveler styles there is

    right: { if is_leveler() then (if card.pt_2 != "" then 277 else 342) else if not is_modal() then card_style.level_2_text.left else card_style.level_2_text.left + (if not modal_flavor() and not modal_rules() then 0.5 else 1) * (if is_map() then 287 else 314) }

Here right depends on left, and the same for bottom depending on top.

It seems that the properties are evaluated in the order [bottom, height, top, right, width, left], at least in the code compiled by visual studio 2019. So right is updated before left is. This is the reverse order from which they are written in the source code, and it might explain the difference with other versions of mse that were built with other compilers.

I could change the evaluation order to what it was before and make sure that it stays consistent. But ideally you shouldn't depend on it. Similarly, the order of evaluation of different styles might change in the future

**Comment by twanvl** [comment]
The order of updates is now [left, width, right, top, height, bottom]. This fixes the leveler card.

The modal card still jumps around sometimes.

**Comment by CajunAvenger** [comment]
I see, I had thought MSE was doing something to figure out a sort of order of dependencies because I hadn't run into the issue before. If there is a fixed order then I can adjust the stylesheet code to work with that, and try another run at that code to avoid needing it.

For the modal card, I have now gotten a scripted text mask working for it, so either that or the addition of #23 will fix the weirdness with that specific issue.

Everything here then seems to be wrapped so I'll close this.
